name: Build & Deploy (Koyeb)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    outputs:
      image: ${{ steps.meta.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: meta
        run: |
          owner="${GITHUB_REPOSITORY_OWNER,,}"
          repo="${GITHUB_REPOSITORY##*/}"
          repo="${repo,,}"
          echo "image=${REGISTRY}/${owner}/${repo}:latest" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2

      - name: Deploy to Koyeb (create or update service)
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
          KOYEB_ORG: ${{ secrets.KOYEB_ORG }}
          KOYEB_APP: ${{ secrets.KOYEB_APP }}
          KOYEB_SERVICE: ${{ secrets.KOYEB_SERVICE }}
          IMAGE: ${{ needs.build-and-push.outputs.image }}
        run: |
          set -euo pipefail

          # Login with token and target organization (org ID)
          koyeb login --token "$KOYEB_API_TOKEN" --organization "$KOYEB_ORG"

          # Ensure the app exists (scoped to the org)
          koyeb apps get "$KOYEB_APP" --organization "$KOYEB_ORG" >/dev/null 2>&1 \
            || koyeb apps create "$KOYEB_APP" --organization "$KOYEB_ORG"

          # Create or update the service on the Free instance
          if koyeb services get "$KOYEB_APP/$KOYEB_SERVICE" --organization "$KOYEB_ORG" >/dev/null 2>&1; then
            koyeb services update "$KOYEB_APP/$KOYEB_SERVICE" \
              --docker "$IMAGE" \
              --routes "/:80" \
              --instance-type "free" \
              --organization "$KOYEB_ORG"
          else
            koyeb services create "$KOYEB_SERVICE" \
              --app "$KOYEB_APP" \
              --docker "$IMAGE" \
              --routes "/:80" \
              --instance-type "free" \
              --organization "$KOYEB_ORG"
          fi
