name: Build & Deploy (Koyeb)

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    outputs:
      image: ${{ steps.meta.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: meta
        run: |
          owner="${GITHUB_REPOSITORY_OWNER,,}"
          repo="${GITHUB_REPOSITORY##*/}"
          repo="${repo,,}"
          echo "image=${REGISTRY}/${owner}/${repo}:latest" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Koyeb (Dockerized CLI)
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }} # must be a USER token
          KOYEB_APP: ${{ secrets.KOYEB_APP }}
          KOYEB_SERVICE: ${{ secrets.KOYEB_SERVICE }}
          IMAGE: ${{ needs.build-and-push.outputs.image }}
        run: |
          set -euo pipefail

          # Sanity check
          if [ -z "${KOYEB_API_TOKEN:-}" ]; then
            echo "KOYEB_API_TOKEN is empty. Add it as a repository secret."; exit 1;
          fi

          # Helper to run koyeb CLI via Docker with the token
          k() { docker run --rm -i koyeb/koyeb-cli:latest "$@" --token "$KOYEB_API_TOKEN"; }

          # Ensure app exists
          if ! k apps get "$KOYEB_APP" >/dev/null 2>&1; then
            k apps create "$KOYEB_APP"
          fi

          # Create or update the service on the free instance
          if k services get "$KOYEB_APP/$KOYEB_SERVICE" >/dev/null 2>&1; then
            k services update "$KOYEB_APP/$KOYEB_SERVICE" \
              --docker "$IMAGE" \
              --routes "/:80" \
              --instance-type "free"
          else
            k services create "$KOYEB_SERVICE" \
              --app "$KOYEB_APP" \
              --docker "$IMAGE" \
              --routes "/:80" \
              --instance-type "free"
          fi
